### ISSUE TITLE
Permission denied error when building v.0.3.0

### ISSUE THREAD

**Issue by mKay00** [marcelwa/fiction#4]
When I try to build the project with the "make" command, I get the following error:

> Scanning dependencies of target z3
[  3%] Generating z3/lib/libz3.so
/bin/sh: 1: scripts/mk_make.py: Permission denied
CMakeFiles/z3.dir/build.make:60: recipe for target 'z3/lib/libz3.so' failed
make[2]: *** [z3/lib/libz3.so] Error 126
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/z3.dir/all' failed
make[1]: *** [CMakeFiles/z3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I tried it in WSL and in a docker container, both with Ubuntu 18.04. If I checkout an older version (v.0.2.1) the build works after a submodule update.

**Comment by marcelwa** [comment]
Thanks for commenting. Please try to remove the old Z3 build via
```sh
rm -rf libs/z3/build
```
in fiction's root folder before triggering a new build.

**Comment by mKay00** [comment]
This doesn't work. I use a fresh clone of the repository (like in my dockerfile in PR #5) with the command
> git clone --recursive https://github.com/marcelwa/fiction.git

and then use the commands
>cd fiction
mkdir build
cd build
cmake ..
make

If I do this there is no build folder in libs/z3/.

**Comment by marcelwa** [comment]
Ah I see what the issue might be then. Seems like CMake was unable to detect your Python installation. If you can't make CMake to recognize Python correctly, the following workaround might fix your problem. Navigate to `fiction/libs/z3/` and execute
```sh
python scripts/mk_make.py --prefix=<PATH_TO_FICTION_FOLDER>/build/z3/
cd build
make
make install
```
Afterwards, you should be good to build fiction via `make fiction` in your build folder.

**Comment by mKay00** [comment]
With this workaround I am able to build it.

**Comment by marcelwa** [comment]
Commit bc3116e1b2ed9c599362fac019b04727f19852a8 should render the workaround unnecessary.
